name: ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v3
      -
        name: Setup Python
        uses: actions/setup-python@v3
      -
        name: precommit
        uses: pre-commit/action@v3.0.0

  docker-build:
    runs-on: ubuntu-latest
    needs: precommit
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: magmax/sekura-agent-fake:latest
